name: Sync Fork

# This runs every day on 1801 UTC
on:
  schedule:
    - cron: '1 18 * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses actions/checkout@v2

    - name: Sync and merge upstream repository with your current repository
      uses: dabreadman/sync-upstream-repo@v1.3.0
      with:
        # URL of gitHub public upstream repo
        upstream_repo: https://github.com/autowarefoundation/autoware_launch
        upstream_branch: main
        downstream_branch: main
        token: ${{ secrets.GITHUB_TOKEN }}
